language: php
php:
  - 5.6
services:
  - mysql
before_script:
  - composer install --no-interaction
  - npm install -g casperjs
#  - git clone git://github.com/n1k0/casperjs.git ~/casperjs
script:
#  - bin/phpcs -p --standard=PSR2 --extensions=php ./src
  - php -S localhost:8000 &
  - echo "localhost:8000" >> casperDomain.txt
#  - casperjs test casperTest.js