language: php
php:
  - 5.6
services:
  - mysql
before_script:
  - mysql -e "create database hotels;"
  - mysql hotels < hotels.sql
  - cp app/config/parameters.yml.travis app/config/parameters.yml
  - composer install --no-interaction
  - npm install -g casperjs
script:
#  - bin/phpcs -p --standard=PSR2 --extensions=php ./src
  - php -S 127.0.0.1:8000 &
  - echo "http://127.0.0.1:8000/" > casperDomain.txt
  - casperjs test casperTest.js