language: php
php:
  - 5.6
services:
  - mysql
before_script:
  - mysql -e "create database hotels;"
  - mysql hotels < hotels.sql
  - echo "parameters:
              database.driver:        mysql
              database.host:          127.0.0.1
              database.port:          3306
              database.name:          hotels
              database.user:          root
              database.password:

              kernel.secret:          vaECGenliFtRwa6wMZnEZni4qxtKbGZ

              fork.debug_email:       info@hotel.dev.lt
              fork.debug_message:     'Internal error.'
              fork.version:           '3.9.5'

              site.protocol:          http
              site.domain:            localhost:8000
              site.default_title:     Fork CMS
              site.multilanguage:     false
              site.default_language:  en
              site.path_www:          %kernel.root_dir%/..
              site.path_library:      %site.path_www%/library

              action.group_tag:       \@actiongroup
              action.rights_level:    7" > app/config/parameters.yml
  - composer install --no-interaction
  - npm install -g casperjs
#  - git clone git://github.com/n1k0/casperjs.git ~/casperjs
script:
#  - bin/phpcs -p --standard=PSR2 --extensions=php ./src
  - php -S localhost:8000 &
  - echo "localhost:8000" > casperDomain.txt
  - casperjs test casperTest.js